import timeit

data = "Usa:English," \
    "Brazil:Portuguese," \
    "Spain:Spanish," \
    "Italy:Italian," \
    "France:French," \
    "Germany:German," \
    "Poland:Polish," \
    "Russia:Russian," \
    "China:Mandarin," \
    "Japan:Japanese," \
    "Korea:Korean," \
    "India:Hindi," \
    "Thailand:Thai," \
    "Vietnam:Vietnamese," \
    "Indonesia:Indonesian," \
    "Philippines:Filipino," \
    "Malaysia:Malay," \
    "Singapore:English," \
    "Canada:English," \
    "Mexico:Spanish," \
    "Argentina:Spanish," \
    "Chile:Spanish," \
    "Peru:Spanish," \
    "Colombia:Spanish," \
    "Venezuela:Spanish," \
    "Ecuador:Spanish," \
    "Bolivia:Spanish," \
    "Uruguay:Spanish," \
    "Paraguay:Spanish," \
    "Australia:English," \
    "NewZealand:English," \
    "SouthAfrica:English," \
    "Egypt:Arabic," \
    "Morocco:Arabic," \
    "Algeria:Arabic," \
    "Nigeria:English," \
    "Kenya:English," \
    "Ethiopia:Amharic," \
    "Turkey:Turkish," \
    "Iran:Persian," \
    "Iraq:Arabic," \
    "SaudiArabia:Arabic," \
    "UnitedArabEmirates:Arabic," \
    "Qatar:Arabic," \
    "Kuwait:Arabic," \
    "Lebanon:Arabic," \
    "Jordan:Arabic," \
    "Israel:Hebrew," \
    "Greece:Greek," \
    "Portugal:Portuguese," \
    "Sweden:Swedish," \
    "Norway:Norwegian," \
    "Denmark:Danish," \
    "Finland:Finnish," \
    "Hungary:Hungarian," \
    "Czech:Czech," \
    "Slovakia:Slovak," \
    "Romania:Romanian," \
    "Bulgaria:Bulgarian," \
    "Serbia:Serbian," \
    "Croatia:Croatian," \
    "Slovenia:Slovenian," \
    "Bosnia:Bosnian," \
    "Ukraine:Ukrainian," \
    "Belarus:Belarusian," \
    "Lithuania:Lithuanian," \
    "Latvia:Latvian," \
    "Estonia:Estonian," \
    "Iceland:Icelandic," \
    "Ireland:English," \
    "Belgium:Dutch," \
    "Netherlands:Dutch," \
    "Austria:German," \
    "Switzerland:German," \
    "Luxembourg:Luxembourgish," \
    "Malta:Maltese," \
    "Cyprus:Greek," \
    "NewCaledonia:French," \
    "Fiji:English," \
    "SolomonIslands:English," \
    "Samoa:Samoan," \
    "Tonga:Tongan," \
    "Kiribati:English," \
    "Nauru:Nauruan," \
    "Palau:Palauan," \
    "Marshall:Marshallese," \
    "Micronesia:English," \
    "Vanuatu:Bislama," \
    "Cambodia:Khmer," \
    "Laos:Lao," \
    "Myanmar:Burmese," \
    "Pakistan:Urdu," \
    "Bangladesh:Bengali," \
    "SriLanka:Sinhala," \
    "Nepal:Nepali," \
    "Bhutan:Dzongkha," \
    "Afghanistan:Dari," \
    "Tajikistan:Tajik," \
    "Kyrgyzstan:Kyrgyz," \
    "Kazakhstan:Kazakh," \
    "Uzbekistan:Uzbek," \
    "Turkmenistan:Turkmen," \
    "Mongolia:Mongolian," \
    "Taiwan:Mandarin," \
    "HongKong:Cantonese," \
    "Macau:Cantonese," \
    "Brunei:Malay," \
    "EastTimor:Tetum," \
    "PapuaNewGuinea:English"

def get_language(country):
    pairs = data.split(",")
    for p in pairs:
        c, l = p.strip().split(":")
        if c == country:
            return l
    return None